#IRIS data set
read.csv("IRISdata.txt")
IRIS <- read.csv("IRISdata.txt")
IRIS
IRISdata <- read.csv("~/R Programs/IRIS/IRISdata.txt", header=FALSE)
View(IRISdata)
data("iris")
view(iris)
irisa <- lapply(iris[ ,c('Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width')], scale)
summary(irisa)
head(irisa)
sd(irisa$Sepal.Length)
sd(irisa$Sepal.Width)
library(dplyr)
library(ggplot2)
ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point(aes(color = Species))
ggplot(iris, aes(Petal.Width, Petal.Length)) + geom_point(aes(color = Species))
set.seed(2345)
irisa <- data.frame(irisa)
irisa
train.irisa <- sample_frac(irisa, 0.7)
test.irisa <- irisa[-as.numeric(rownames(train.irisa)), ]
library(kknn)
kknn.3 <- kknn(Species ~., train = train.irisa, test = test.irisa, k = 3)
data("iris")
str(iris)
table(iris$Species)
iris[ , c("Sepal.Width", "Sepal.Length", "Petal.Width", "Petal.Length")] <- lapply(iris[,c("Sepal.Width", "Sepal.Length", "Petal.Width", "Petal.Length")], scale)
summary(irisa)
summary(iris)
set.seed(2345)
train.iris = sample_frac(iris,0.7)
test.iris = iris[-as.numeric(rownames(train.iris)),]
knn.3 <- kknn(Species ~., train = train.iris, test = test.iris, k = 3)
summary(knn.3)
test.iris$predicted = predict(knn.3)
test.iris$correct = test.iris$Species == test.iris$predicted
100 * sum(test.iris$correct/nrow(test.iris))
ggplot(test.iris, aes(Sepal.Width, Sepal.Length)) + geom_point(aes(color = predicted, shape = correct))
ggplot(test.iris, aes(Petal.Width, Petal.Length)) + geom_point(aes(color = predicted, shape = correct))
data("iris")
str(iris)
